name: OpenJDK CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main, ci ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-and-compare:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          path: openjdk

      # Runs a single command using the runners shell
      - name: Install Modus
        run: cargo install modus
        
      - name: Build Linux images
        run: ~/.cargo/bin/modus build $GITHUB_WORKSPACE/openjdk -f <(cat $GITHUB_WORKSPACE/openjdk/*.Modusfile) 'openjdk(A, B, C)' --json > build.json

      - name: Tag images
        run: jq '.[] | [.digest, (.args | join("-"))] | join(" ")' build.json | xargs -I % sh -c 'docker tag %'

      - name: Install container-diff
        run: |
          curl -LO https://storage.googleapis.com/container-diff/latest/container-diff-linux-amd64
          sudo install container-diff-linux-amd64 /usr/local/bin/container-diff

      - name: Compare image sizes/filesystem
        run: jq '.[].args | join("-")' build.json | xargs -I % sh -c 'container-diff diff openjdk:% daemon://% --type=size --type=file'

      - name: View docker images
        run: docker images
